### ISSUE TITLE
Can you upstream the ability to use plugin block?

### ISSUE THREAD

**Issue by AceHack** [eirnym/js2p-gradle#1]
thanks.

**Comment by eirnym** [comment]
@AceHack Thank you for a question, 

I don't see if it would ever happen, due to no answer in my issue on this and little interest on this plugin of the author. Gradle publishing requires to use gradle, not maven, and author doesn't use it at all. Using the plugin from different repository in corporative environment is a big pain. 

I'll make sure that I go as close to versions as possible.

Some of the goals of this plugin are:
* Publish to official gradle plugin repository
* Make it compatible with Gradle 5.6+
* Rewrite interface to make it human-writable 
* Add ability to specify dependencies for this plugin when using custom annotations
