### ISSUE TITLE
Send a pull request to original repo

### ISSUE THREAD

**Issue by AlexTrotsenko** [eirnym/js2p-gradle#2]
@eirnym  this more a question if you are planning to contributed back to the original repo of jsonschema2pojo or to keep this as a separate plugin ?

I guess it would be for the best of everyone to have latest version of jsonschema2pojo and your improvements to the build script.

What do you think?

See https://github.com/joelittlejohn/jsonschema2pojo/issues/896#issuecomment-611504009

**Comment by eirnym** [comment]
@AlexTrotsenko Thank you for a question. 

Long story short, I don't see this plugin merged back. Currently, I'm subscribed on release notifications of jsonschema2pojo and have full support for the latest version. When new version is out, I'll update the plugin.

Long story: 

There's few major obstacles there to merge the plugin back, and the resolution proposition at the end. 

First is quite obvious. it's support for official gradle repo plugins.gradle.org. It's possible to publish there from Gradle, but not from Maven, or at least I haven't found proper way to proceed with whole procedure using just Maven.
Nevertheless, it can be easily done in the opposite way, converting all POMs to gradle.Looking on how the `pom.xml` files are organised in the original repository, I don't believe that the author will convert all POMs to build.gradle. Also I see that transformation as a long way as it doesn't guarantee the author have the same or even similar POMs in the maven repository. This is the second obstacle. 

The third reason is continuation of support for Gradle 2.3-5.5.x which is included in the original project. I don't see feasible and reasonable to support both methods, and I don't want to just remove the support for those who don't want (or can't for some reasons) to upgrade their build environment. I know a few such projects in various enterprise companies, so and it'd take not a single day to migrate, to upgrade the project even if library API hasn't changed and just security patch was applied.

The forth reason is I want to make changes to the public API and interaction with a user as plugin will grow, make it more human readable and writable.

I see a compromise for resolving your issue is to make this plugin as "official one", like it's done for [checker framework](https://checkerframework.org). This would ease the tension you mentioned and resolve most issues about plugin upgrade. However, I got no response from the author, so currently I know if it would be possible. 

I hope I've answered your questions.

**Comment by AlexTrotsenko** [comment]
@eirnym  thanks for the info, let's continue discussion in original repo together with @joelittlejohn

**Comment by eirnym** [comment]
@renannprado as we agreed with @joelittlejohn, this will be an official gradle plugin. No need to worry about "outdated versions" or anything else.

I don't understand the idea to merge everything into the single repository. There's many examples where you use official plugins maintained by other people in separate repositories. These examples include Lombok, Checker Framework and any xjc plugin.

**Comment by renannprado** [comment]
@eirnym if you finally could get to a common ground on this subject all good :)
